### ISSUE TITLE
Benchmark Ancestry Performance

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#204]
Currently, the ancestry module appears about 1-2 order of magnitude slower than either indexing or annotation, with annotation of 13,000 variants and 3 genotypes taking approximately 2 seconds, indexing about 10 seconds, and ancestry 45 seconds. Given the much lower IO requirements for ancestry vs either annotation or indexing, this is surprising. This performance gap also makes for a meaningfully worse user experience, and will also limit the kinds of queries users can execute as the user waits on ancestry to complete. 

If we scale this to even 1000 genomes size data, which is small by today's standards, how does ancestry calculation scale? What if we have Wingo-scale data (~20,000 genomes). Where is the performance bottleneck, VCF parsing, data frame manipulation, or RandomForestClassifier?
 - If VCF parsing, we should move to Rust vcf parser (we need this for Bystro anyway)
 - If pandas, we should try polars or stick with numpy directly
 - If RandomForestClassifier we should try XGBoost

What we learn here will be used to improve ancestry runtime performance and make future architectural decisions.

**Comment by poneill** [comment]
It looks like https://github.com/bystrogenomics/bystro/blob/1c8e78467a4d5fc953bc7da5019be0dea9a5845a/python/python/bystro/ancestry/train.py#L142 was a perf regression: we're now splitting the line (which takes 95% of the function's wall time) before checking if the line pertains to a variant we want to read.

In the short term I'd propose we:
- revert to earlier strategy of checking if we need line before parsing it
- put _parse_vcf under a perf test to catch future regressions
- add additional logging to the ancestry listener so it's easier to diagnose performance issues

In the long term we should probably get off parsing VCFs in python.

**Comment by poneill** [comment]
> Are we ready to close this then?

It depends on the timeline for the rust parser, I guess.  If we need a short-term fix, I submitted a PR to fix (and test) the perf regression.
