### ISSUE TITLE
[task list][proteomics] Protein Abundance Task List

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#223]
Background: One of the major deliverables for Gates is integration of proteomic data with genetic data: the ability to filter proteomic data by genetic annotations, the ability to filter genetic data by protein abundance values.

### Deliverable:
The deliverable for Sprint 1 are minimally **Step 1** below, ideally Step 2 as well (Step 2 is a stretch goal)

### Step 1
- [x] Ingest combined protein abundance file 
- [x] #225
- [x] #226
- [x] #228
- [x] #229

### Step 2
- [ ] #230
   - [ ] #231
   - [ ] #232
   - [ ] #233
   - [ ] #234
 - [x] Authenticated scroll query

### Example Queries We Need To Support
1. Select all missense mutations in the (padded) regions for the genes found in the combined protein abundance file.
2. Same as query 1, but do so only for specific individuals, identified from the combined protein abundance file, or from a mapping of protein abundance file to sample name.

**Comment by cristinaetrv** [comment]
Querying by 'nearest' will be moved to Q1 2024
