### ISSUE TITLE
Create protein abundance filtering batch submission python API beanstalkd listener/handler

### ISSUE THREAD

**Issue by poneill** [bystrogenomics/bystro#226]
Much like we have with search, indexing, and ancestry, we will create another batch submission API listener/handler. 

The job is processed through our API server, which results in a beanstalkd submission to our cluster, where the filtering of the protein abundance file happens, resulting in a new protein abundance file written to disk, and a path for that file returned to the user.

- We re-use the code (duplication is OK for v1) from bystro/search/save/handler.py for handling the scrolling through annotation index
- We pull down the annotation index as in bystro/search/save/handler.py, and add the protein abundance values
- We persist these values on EFS, return a path to the results

**Comment by cristinaetrv** [comment]
Persisting values on EFS and returning a path to the results has been moved to a separate ticket - #325
