### ISSUE TITLE
Annotation Sprint 1 Task List

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#241]
- [x] #256
  - Chat with Dave, Thomas, others at Emory, look at VEP (we'll want feature parity at least)
  - Results of feedback/survey/interviews will go into internal docs
- [ ] #257
- [x] #258
  - Goes into wiki or ANNOTATION.md
- [x] #259
  - Store the databases in S3, updating documentation (INSTALL.md) with the correct database link
- [x] #260
  - Store the databases in S3, updating documentation (INSTALL.md) with the correct database link
- [x] #261
  - Document in internal docs, and create follow on tickets
- [x] #262
   - Document unit test coverage in internal docs
- [x] #263
   - We already have the code for this, https://github.com/bystrogenomics/bystro/blob/master/lib/Seq/Output/Delimiters.pm#L37, goal of this. task is to re-assure ourselves that this works, and document the behavior in BUILD.md

**Comment by cristinaetrv** [comment]
Closing after sprint 1 completed. The remaining item has been moved to Sprint 3.
