### ISSUE TITLE
Documentation: Gather feedback on annotations to add for V1.0.0 release (do we add all gnomad annotations, etc)

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#256]
* Identify and document the annotations we'll launch with for December.

**Comment by akotlar** [comment]
Feedback from Dave on Gnomad:
- All of it, every pop. We'll keep storing the an and af annotations for each population

**Comment by poneill** [comment]
Just verifying here that the feedback's been collected.
