### ISSUE TITLE
Documentation: CLI bystro users can already select subsets of annotation, by editing the YAML config file for the assembly in use. Document how to do this.

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#258]

**Comment by akotlar** [comment]
Done: https://github.com/bystrogenomics/bystro/wiki/Annotation

**Comment by cristinaetrv** [comment]
Added a few small changes suggestions to improve clarity directly - can be reverted in edit page history if desired.

Otherwise, lgtm!
