### ISSUE TITLE
DB Build: Update hg38 database with CADD & other missing b10 database tracks / features

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#259]
The goal is to bring hg38 master branch db up to date with b10. In this version of the database, we still have the UNIT SEPARATOR overlap delimiter.

**Comment by akotlar** [comment]
I will put on the dev annotator instance shortly

**Comment by akotlar** [comment]
I realized that nearest.refSeq and nearestTss.refSeq were incorrectly specified in the config file (well, specification was ok, but the input files weren't present on disk), so am rebuilding.

**Comment by cristinaetrv** [comment]
Looks good and appears to be working as expected. 

We discussed adding the option for the query 'intergenic' to map to '!refSeq.siteType' but that is outside of the scope of the current issue and things of this nature could be addressed in future issues.
