### ISSUE TITLE
Backend: Ensure that overlap delimiter is properly replaced with another character during database build. Write unit test to prove correctness if one doesn't exist

### ISSUE THREAD

**Issue by akotlar** [bystrogenomics/bystro#263]

**Comment by akotlar** [comment]
This will slip to Sprint 2 from Sprint 1, and will be expanded to converting the delimiter to ; or /

**Comment by cristinaetrv** [comment]
Sounds good, please link the follow-up ticket to this one to track the progress of this issue.
