### ISSUE TITLE
Clean project branches

### ISSUE THREAD

**Issue by wingolab** [bystrogenomics/bystro#294]
### Background:
There are a number of branches that have unclear use or purpose. I also accidentally created a branch, perl-docker, that should be removed, too.

### Completion Criteria:
Prune branches that are unused or no longer needed (e.g., merged).

**Comment by akotlar** [comment]
I removed all unneeded branches. In general we should use the forking model to avoid adding unnecessary development branches to this repo. We've outlined that approach in CONTRIBUTING.md: https://github.com/bystrogenomics/bystro/blob/master/CONTRIBUTING.md
